// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kademlia_service.proto

#include "include/kademlia_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_kademlia_5fservice_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_kademlia_5fservice_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Neighbors_node;
}  // namespace protobuf_kademlia_5fservice_2eproto
namespace kademlia {
class TargetDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Target>
      _instance;
} _Target_default_instance_;
class Neighbors_nodeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Neighbors_node>
      _instance;
} _Neighbors_node_default_instance_;
class NeighborsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Neighbors>
      _instance;
} _Neighbors_default_instance_;
}  // namespace kademlia
namespace protobuf_kademlia_5fservice_2eproto {
static void InitDefaultsTarget() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::kademlia::_Target_default_instance_;
    new (ptr) ::kademlia::Target();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::kademlia::Target::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Target =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsTarget}, {}};

static void InitDefaultsNeighbors_node() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::kademlia::_Neighbors_node_default_instance_;
    new (ptr) ::kademlia::Neighbors_node();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::kademlia::Neighbors_node::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Neighbors_node =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNeighbors_node}, {}};

static void InitDefaultsNeighbors() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::kademlia::_Neighbors_default_instance_;
    new (ptr) ::kademlia::Neighbors();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::kademlia::Neighbors::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Neighbors =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsNeighbors}, {
      &protobuf_kademlia_5fservice_2eproto::scc_info_Neighbors_node.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Target.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Neighbors_node.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Neighbors.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Target, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Target, target_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Target, sender_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Target, sender_address_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Target, sender_port_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Target, time_stamp_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Neighbors_node, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Neighbors_node, node_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Neighbors_node, address_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Neighbors_node, port_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Neighbors, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Neighbors, neighbors_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::kademlia::Neighbors, time_stamp_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::kademlia::Target)},
  { 10, -1, sizeof(::kademlia::Neighbors_node)},
  { 18, -1, sizeof(::kademlia::Neighbors)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::kademlia::_Target_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::kademlia::_Neighbors_node_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::kademlia::_Neighbors_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "kademlia_service.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026kademlia_service.proto\022\010kademlia\"o\n\006Ta"
      "rget\022\021\n\ttarget_id\030\001 \001(\014\022\021\n\tsender_id\030\002 \001"
      "(\014\022\026\n\016sender_address\030\003 \001(\t\022\023\n\013sender_por"
      "t\030\004 \001(\t\022\022\n\ntime_stamp\030\005 \001(\004\"\204\001\n\tNeighbor"
      "s\022+\n\tneighbors\030\001 \003(\0132\030.kademlia.Neighbor"
      "s.node\022\022\n\ntime_stamp\030\002 \001(\004\0326\n\004node\022\017\n\007no"
      "de_id\030\001 \001(\014\022\017\n\007address\030\002 \001(\t\022\014\n\004port\030\003 \001"
      "(\t2F\n\017KademliaService\0223\n\010FindNode\022\020.kade"
      "mlia.Target\032\023.kademlia.Neighbors\"\000b\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 362);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "kademlia_service.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_kademlia_5fservice_2eproto
namespace kademlia {

// ===================================================================

void Target::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Target::kTargetIdFieldNumber;
const int Target::kSenderIdFieldNumber;
const int Target::kSenderAddressFieldNumber;
const int Target::kSenderPortFieldNumber;
const int Target::kTimeStampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Target::Target()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kademlia_5fservice_2eproto::scc_info_Target.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:kademlia.Target)
}
Target::Target(const Target& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  target_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.target_id().size() > 0) {
    target_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.target_id_);
  }
  sender_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sender_id().size() > 0) {
    sender_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_id_);
  }
  sender_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sender_address().size() > 0) {
    sender_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_address_);
  }
  sender_port_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sender_port().size() > 0) {
    sender_port_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_port_);
  }
  time_stamp_ = from.time_stamp_;
  // @@protoc_insertion_point(copy_constructor:kademlia.Target)
}

void Target::SharedCtor() {
  target_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_port_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_stamp_ = GOOGLE_ULONGLONG(0);
}

Target::~Target() {
  // @@protoc_insertion_point(destructor:kademlia.Target)
  SharedDtor();
}

void Target::SharedDtor() {
  target_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_port_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Target::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Target::descriptor() {
  ::protobuf_kademlia_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kademlia_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Target& Target::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kademlia_5fservice_2eproto::scc_info_Target.base);
  return *internal_default_instance();
}


void Target::Clear() {
// @@protoc_insertion_point(message_clear_start:kademlia.Target)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  target_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_port_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_stamp_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool Target::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:kademlia.Target)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes target_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_target_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes sender_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_sender_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string sender_address = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sender_address()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sender_address().data(), static_cast<int>(this->sender_address().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "kademlia.Target.sender_address"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string sender_port = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sender_port()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sender_port().data(), static_cast<int>(this->sender_port().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "kademlia.Target.sender_port"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 time_stamp = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &time_stamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:kademlia.Target)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:kademlia.Target)
  return false;
#undef DO_
}

void Target::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:kademlia.Target)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes target_id = 1;
  if (this->target_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->target_id(), output);
  }

  // bytes sender_id = 2;
  if (this->sender_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->sender_id(), output);
  }

  // string sender_address = 3;
  if (this->sender_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sender_address().data(), static_cast<int>(this->sender_address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "kademlia.Target.sender_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->sender_address(), output);
  }

  // string sender_port = 4;
  if (this->sender_port().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sender_port().data(), static_cast<int>(this->sender_port().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "kademlia.Target.sender_port");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->sender_port(), output);
  }

  // uint64 time_stamp = 5;
  if (this->time_stamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->time_stamp(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:kademlia.Target)
}

::google::protobuf::uint8* Target::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:kademlia.Target)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes target_id = 1;
  if (this->target_id().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->target_id(), target);
  }

  // bytes sender_id = 2;
  if (this->sender_id().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->sender_id(), target);
  }

  // string sender_address = 3;
  if (this->sender_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sender_address().data(), static_cast<int>(this->sender_address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "kademlia.Target.sender_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->sender_address(), target);
  }

  // string sender_port = 4;
  if (this->sender_port().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sender_port().data(), static_cast<int>(this->sender_port().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "kademlia.Target.sender_port");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->sender_port(), target);
  }

  // uint64 time_stamp = 5;
  if (this->time_stamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->time_stamp(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kademlia.Target)
  return target;
}

size_t Target::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kademlia.Target)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes target_id = 1;
  if (this->target_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->target_id());
  }

  // bytes sender_id = 2;
  if (this->sender_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->sender_id());
  }

  // string sender_address = 3;
  if (this->sender_address().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sender_address());
  }

  // string sender_port = 4;
  if (this->sender_port().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sender_port());
  }

  // uint64 time_stamp = 5;
  if (this->time_stamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->time_stamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Target::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:kademlia.Target)
  GOOGLE_DCHECK_NE(&from, this);
  const Target* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Target>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:kademlia.Target)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:kademlia.Target)
    MergeFrom(*source);
  }
}

void Target::MergeFrom(const Target& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:kademlia.Target)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.target_id().size() > 0) {

    target_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.target_id_);
  }
  if (from.sender_id().size() > 0) {

    sender_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_id_);
  }
  if (from.sender_address().size() > 0) {

    sender_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_address_);
  }
  if (from.sender_port().size() > 0) {

    sender_port_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_port_);
  }
  if (from.time_stamp() != 0) {
    set_time_stamp(from.time_stamp());
  }
}

void Target::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:kademlia.Target)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Target::CopyFrom(const Target& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kademlia.Target)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Target::IsInitialized() const {
  return true;
}

void Target::Swap(Target* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Target::InternalSwap(Target* other) {
  using std::swap;
  target_id_.Swap(&other->target_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  sender_id_.Swap(&other->sender_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  sender_address_.Swap(&other->sender_address_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  sender_port_.Swap(&other->sender_port_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(time_stamp_, other->time_stamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Target::GetMetadata() const {
  protobuf_kademlia_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kademlia_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Neighbors_node::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Neighbors_node::kNodeIdFieldNumber;
const int Neighbors_node::kAddressFieldNumber;
const int Neighbors_node::kPortFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Neighbors_node::Neighbors_node()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kademlia_5fservice_2eproto::scc_info_Neighbors_node.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:kademlia.Neighbors.node)
}
Neighbors_node::Neighbors_node(const Neighbors_node& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  node_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.node_id().size() > 0) {
    node_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.node_id_);
  }
  address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.address().size() > 0) {
    address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.address_);
  }
  port_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.port().size() > 0) {
    port_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.port_);
  }
  // @@protoc_insertion_point(copy_constructor:kademlia.Neighbors.node)
}

void Neighbors_node::SharedCtor() {
  node_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Neighbors_node::~Neighbors_node() {
  // @@protoc_insertion_point(destructor:kademlia.Neighbors.node)
  SharedDtor();
}

void Neighbors_node::SharedDtor() {
  node_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Neighbors_node::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Neighbors_node::descriptor() {
  ::protobuf_kademlia_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kademlia_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Neighbors_node& Neighbors_node::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kademlia_5fservice_2eproto::scc_info_Neighbors_node.base);
  return *internal_default_instance();
}


void Neighbors_node::Clear() {
// @@protoc_insertion_point(message_clear_start:kademlia.Neighbors.node)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  node_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  port_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Neighbors_node::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:kademlia.Neighbors.node)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes node_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_node_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string address = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_address()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->address().data(), static_cast<int>(this->address().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "kademlia.Neighbors.node.address"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string port = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_port()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->port().data(), static_cast<int>(this->port().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "kademlia.Neighbors.node.port"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:kademlia.Neighbors.node)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:kademlia.Neighbors.node)
  return false;
#undef DO_
}

void Neighbors_node::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:kademlia.Neighbors.node)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes node_id = 1;
  if (this->node_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->node_id(), output);
  }

  // string address = 2;
  if (this->address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->address().data(), static_cast<int>(this->address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "kademlia.Neighbors.node.address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->address(), output);
  }

  // string port = 3;
  if (this->port().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->port().data(), static_cast<int>(this->port().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "kademlia.Neighbors.node.port");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->port(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:kademlia.Neighbors.node)
}

::google::protobuf::uint8* Neighbors_node::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:kademlia.Neighbors.node)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes node_id = 1;
  if (this->node_id().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->node_id(), target);
  }

  // string address = 2;
  if (this->address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->address().data(), static_cast<int>(this->address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "kademlia.Neighbors.node.address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->address(), target);
  }

  // string port = 3;
  if (this->port().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->port().data(), static_cast<int>(this->port().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "kademlia.Neighbors.node.port");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->port(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kademlia.Neighbors.node)
  return target;
}

size_t Neighbors_node::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kademlia.Neighbors.node)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes node_id = 1;
  if (this->node_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->node_id());
  }

  // string address = 2;
  if (this->address().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->address());
  }

  // string port = 3;
  if (this->port().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->port());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Neighbors_node::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:kademlia.Neighbors.node)
  GOOGLE_DCHECK_NE(&from, this);
  const Neighbors_node* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Neighbors_node>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:kademlia.Neighbors.node)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:kademlia.Neighbors.node)
    MergeFrom(*source);
  }
}

void Neighbors_node::MergeFrom(const Neighbors_node& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:kademlia.Neighbors.node)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.node_id().size() > 0) {

    node_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.node_id_);
  }
  if (from.address().size() > 0) {

    address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.address_);
  }
  if (from.port().size() > 0) {

    port_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.port_);
  }
}

void Neighbors_node::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:kademlia.Neighbors.node)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Neighbors_node::CopyFrom(const Neighbors_node& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kademlia.Neighbors.node)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Neighbors_node::IsInitialized() const {
  return true;
}

void Neighbors_node::Swap(Neighbors_node* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Neighbors_node::InternalSwap(Neighbors_node* other) {
  using std::swap;
  node_id_.Swap(&other->node_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  address_.Swap(&other->address_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  port_.Swap(&other->port_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Neighbors_node::GetMetadata() const {
  protobuf_kademlia_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kademlia_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Neighbors::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Neighbors::kNeighborsFieldNumber;
const int Neighbors::kTimeStampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Neighbors::Neighbors()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_kademlia_5fservice_2eproto::scc_info_Neighbors.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:kademlia.Neighbors)
}
Neighbors::Neighbors(const Neighbors& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      neighbors_(from.neighbors_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  time_stamp_ = from.time_stamp_;
  // @@protoc_insertion_point(copy_constructor:kademlia.Neighbors)
}

void Neighbors::SharedCtor() {
  time_stamp_ = GOOGLE_ULONGLONG(0);
}

Neighbors::~Neighbors() {
  // @@protoc_insertion_point(destructor:kademlia.Neighbors)
  SharedDtor();
}

void Neighbors::SharedDtor() {
}

void Neighbors::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Neighbors::descriptor() {
  ::protobuf_kademlia_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kademlia_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Neighbors& Neighbors::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_kademlia_5fservice_2eproto::scc_info_Neighbors.base);
  return *internal_default_instance();
}


void Neighbors::Clear() {
// @@protoc_insertion_point(message_clear_start:kademlia.Neighbors)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  neighbors_.Clear();
  time_stamp_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool Neighbors::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:kademlia.Neighbors)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .kademlia.Neighbors.node neighbors = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_neighbors()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 time_stamp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &time_stamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:kademlia.Neighbors)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:kademlia.Neighbors)
  return false;
#undef DO_
}

void Neighbors::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:kademlia.Neighbors)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .kademlia.Neighbors.node neighbors = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->neighbors_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->neighbors(static_cast<int>(i)),
      output);
  }

  // uint64 time_stamp = 2;
  if (this->time_stamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->time_stamp(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:kademlia.Neighbors)
}

::google::protobuf::uint8* Neighbors::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:kademlia.Neighbors)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .kademlia.Neighbors.node neighbors = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->neighbors_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->neighbors(static_cast<int>(i)), deterministic, target);
  }

  // uint64 time_stamp = 2;
  if (this->time_stamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->time_stamp(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kademlia.Neighbors)
  return target;
}

size_t Neighbors::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kademlia.Neighbors)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .kademlia.Neighbors.node neighbors = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->neighbors_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->neighbors(static_cast<int>(i)));
    }
  }

  // uint64 time_stamp = 2;
  if (this->time_stamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->time_stamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Neighbors::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:kademlia.Neighbors)
  GOOGLE_DCHECK_NE(&from, this);
  const Neighbors* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Neighbors>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:kademlia.Neighbors)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:kademlia.Neighbors)
    MergeFrom(*source);
  }
}

void Neighbors::MergeFrom(const Neighbors& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:kademlia.Neighbors)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  neighbors_.MergeFrom(from.neighbors_);
  if (from.time_stamp() != 0) {
    set_time_stamp(from.time_stamp());
  }
}

void Neighbors::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:kademlia.Neighbors)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Neighbors::CopyFrom(const Neighbors& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kademlia.Neighbors)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Neighbors::IsInitialized() const {
  return true;
}

void Neighbors::Swap(Neighbors* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Neighbors::InternalSwap(Neighbors* other) {
  using std::swap;
  CastToBase(&neighbors_)->InternalSwap(CastToBase(&other->neighbors_));
  swap(time_stamp_, other->time_stamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Neighbors::GetMetadata() const {
  protobuf_kademlia_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_kademlia_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace kademlia
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::kademlia::Target* Arena::CreateMaybeMessage< ::kademlia::Target >(Arena* arena) {
  return Arena::CreateInternal< ::kademlia::Target >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::kademlia::Neighbors_node* Arena::CreateMaybeMessage< ::kademlia::Neighbors_node >(Arena* arena) {
  return Arena::CreateInternal< ::kademlia::Neighbors_node >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::kademlia::Neighbors* Arena::CreateMaybeMessage< ::kademlia::Neighbors >(Arena* arena) {
  return Arena::CreateInternal< ::kademlia::Neighbors >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
